// Notify if crystal is found
IF
  Global("A7STO-TOBQuestCrystal","MYAREA",0)
  Global("A7STO-TOBQuest","GLOBAL",1)
  PartyHasItem("a7_crys")
THEN
  RESPONSE #100
    SetGlobal("A7STO-TOBQuestCrystal","MYAREA",1)
    AddJournalEntry(@10301,QUEST)
    Continue()
END

IF
  Global("A7STO-TOBQuestCrystal","MYAREA",0)
  Global("A7STO-TOBQuest","GLOBAL",0)
  PartyHasItem("a7_crys")
THEN
  RESPONSE #100
    SetGlobal("A7STO-TOBQuestCrystal","MYAREA",1)
    Continue()
END
